spring:
  data:
    mongodb:
      host: mongo-database
      port: 27017
      authentication-database: admin
      username: mongoadmin
      password: password
      database: IMT_Auth
      mechanism: SCRAM-SHA-256